SET PATH=C:\Keil_v5\ARM\ARMCC\Bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\MATLAB\R2021a\bin;C:\Program Files\CMake\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Users\110618038\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\110618038\AppData\Local\Programs\Python\Python310\;C:\Users\110618038\AppData\Local\Microsoft\WindowsApps;;C:\Users\110618038\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\110618038\.dotnet\tools
SET CPU_TYPE=STM32F407VG
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Discovery
SET CPU_CLOCK=0x007A1200
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "c:\keil_v5\0executable\main.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "c:\keil_v5\0executable\stm32f4x7_eth_bsp.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "c:\keil_v5\0executable\stm32f4xx_it.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "c:\keil_v5\0executable\system_stm32f4xx.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "c:\keil_v5\0executable\lab612_tim.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "c:\keil_v5\0executable\lab612_tim_it.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "c:\keil_v5\0executable\lab612_adc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmLink" --Via "C:\Keil_v5\0Executable\Project.lnp"
